"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider } from '@clerk/nextjs'
import {CartContext} from './_context/CartContext'
import { useState,Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({ children }) {
  const [cart,setCart]=useState([])
  return (
    <ClerkProvider>
      <CartContext.Provider value={{cart,setCart}}>
        <html lang="en">
          <body className={inter.className}>
            <Header/>
            <Suspense>
              {children}
            </Suspense>
            <Footer/>
          </body>
        </html>
      </CartContext.Provider>
    </ClerkProvider>
  );
}
